version: '3'

# volumes:
#   local_postgres_data: {}
#   local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: quda_local_django
    container_name: django
    # depends_on:
    #   - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      # - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  pyspark:
    image: jupyter/pyspark-notebook:150731d32f85
    container_name: pyspark
    ports:
      - "8888:8888"

  docs:
    image: quda_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./quda:/app/quda:z
    ports:
      - "7000:7000"

  redis:
    image: redis:5.0
    container_name: redis

  mongo:
    image: mongo:4.2
    container_name: mongo

  celeryworker:
    <<: *django
    image: quda_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: quda_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: quda_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
