version: '3'

volumes:
  portainer_data: {}
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8001:80"
    depends_on:
      - django
      - quasar
    volumes:
      - ./backend/quda/media/:/media/
      - ./backend/quda/staticfiles/:/static/
      - ./nginx/local.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure

  django: &django
    container_name: django
    image: hcd_local_django
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app:z
    working_dir: /app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8002:8002"
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start

  quasar:
    container_name: quasar
    image: hcd_local_quasar
    working_dir: /app
    volumes:
      - ./frontend:/app:z
    env_file:
      - ./.envs/.local/.quasar
    ports:
      - "8003:8003"
    build:
      context: .
      dockerfile: ./docker/local/quasar/Dockerfile
    command: npm run serve
    restart: on-failure

  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: hcd_local_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    container_name: redis
    image: redis:5.0

  mongo:
    container_name: mongo
    image: mongo:4.2

  celeryworker:
    <<: *django
    container_name: celeryworker
    image: hcd_local_celeryworker
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: celerybeat
    image: hcd_local_celerybeat
    depends_on:
      - redis
      - celeryworker
      - django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    container_name: flower
    image: hcd_local_flower
    depends_on:
      - celeryworker
      - django
    ports:
      - "5555:5555"
    command: /start-flower

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
      - 8009:8009
    restart: always
    logging:
      driver: none


