# Generated by Django 3.0.10 on 2020-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('creationDateTime', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creacion de la configuracion del perfilamiento.')),
                ('initialDateTime', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de la ejecucion del proceso para el perfilamiento configurado.', null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, help_text='Fecha y hora de termino de la ejecucion del proceso para el perfilamiento configurado.', null=True)),
            ],
            options={
                'verbose_name': 'Perfilamiento',
                'verbose_name_plural': 'Perfilamientos',
                'permissions': [('Can_View__Profiling', 'Ve perfilamientos'), ('Can_Create__Profiling', 'Crea perfilamientos'), ('Can_Update__Profiling', 'Modifica perfilamientos'), ('Can_Delete__Profiling', 'Elimina perfilamientos')],
                'abstract': False,
            },
        ),
    ]
