# Generated by Django 3.0.10 on 2020-10-19 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('creationDateTime', models.DateTimeField(auto_now_add=True)),
                ('initialDateTime', models.DateTimeField(blank=True, null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfilamiento',
                'verbose_name_plural': 'Perfilamientos',
                'permissions': [('Can_View__Profiling', 'Ve perfilamientos'), ('Can_Create__Profiling', 'Crea perfilamientos'), ('Can_Update__Profiling', 'Modifica perfilamientos'), ('Can_Delete__Profiling', 'Elimina perfilamientos')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilingFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quda.File')),
                ('initialDateTime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('profiling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prfl.Profiling')),
            ],
            options={
                'verbose_name': 'Archivo de Perfilamiento',
                'verbose_name_plural': 'Archivos de Perfilamiento',
                'permissions': [('Can_View__ProfilingFile', 'Ve archivos de perfilamiento'), ('Can_Create__ProfilingFile', 'Crea archivos de perfilamiento'), ('Can_Update__ProfilingFile', 'Modifica archivos de perfilamiento'), ('Can_Delete__ProfilingFile', 'Elimina archivos de perfilamiento')],
                'abstract': False,
            },
            bases=('quda.file',),
        ),
        migrations.CreateModel(
            name='ProfilingRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('checkBlank', models.BooleanField(default=False)),
                ('checkFloat', models.BooleanField(default=False)),
                ('checkInt', models.BooleanField(default=False)),
                ('checkDate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Regla de perfilamiento',
                'verbose_name_plural': 'Reglas de perfilamiento',
                'permissions': [('Can_View__ProfilingRules', 'Ve reglas de perfilamiento'), ('Can_Create__ProfilingRules', 'Crea reglas de perfilamiento'), ('Can_Update__ProfilingRules', 'Modifica reglas de perfilamiento'), ('Can_Delete__ProfilingRules', 'Elimina reglas de perfilamiento')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilingFileColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('columnIndex', models.IntegerField(default=0)),
                ('blanks', models.IntegerField(default=0)),
                ('profilingFile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prfl.ProfilingFile')),
                ('profilingRule', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='prfl.ProfilingRules')),
            ],
            options={
                'verbose_name': 'Columna de archivos de perfilamiento',
                'verbose_name_plural': 'Columnas de archivos de perfilamiento',
                'permissions': [('Can_View__ProfilingFileColumn', 'Ve columnas de archivos de perfilamiento'), ('Can_Create__ProfilingFileColumn', 'Crea columnas de archivos de perfilamiento'), ('Can_Update__ProfilingFileColumn', 'Modifica columnas de archivos de perfilamiento'), ('Can_Delete__ProfilingFileColumn', 'Elimina columnas de archivos de perfilamiento')],
                'abstract': False,
            },
        ),
    ]
