# Generated by Django 3.0.10 on 2020-11-03 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quda', '0001_initial'),
        ('prfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quda.File')),
                ('initialDateTime', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de inicio de la ejecucion del procesamiento del archivo.', null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de termino de la ejecucion del procesamiento del archivo.', null=True)),
                ('analysis', models.TextField(blank=True, help_text='Informacion referente al tiempo de ejecucion y generacion del analisis del archivo.', null=True)),
                ('table', models.TextField(blank=True, null=True)),
                ('variables', models.TextField(blank=True, help_text='Informacion estadistica referente a las columnas del archivo analisado.', null=True)),
                ('scatter', models.TextField(blank=True, null=True)),
                ('correlations', models.TextField(blank=True, help_text='Informacion estadistica del a correlacion de 2 o mas columnas del archivo a analizar.', null=True)),
                ('missing', models.TextField(blank=True, help_text='Informacion estadistica de los registros vacios o nulos por columna.', null=True)),
                ('messages', models.TextField(blank=True, help_text='Mensajes informativos referente a la composicion estadistica de los datos de cada columna del archivo.', null=True)),
                ('package', models.TextField(blank=True, null=True)),
                ('sample', models.TextField(blank=True, null=True)),
                ('duplicates', models.TextField(blank=True, help_text='Informacion estadistica de los registros duplicados por columna.', null=True)),
                ('profiling', models.ForeignKey(blank=True, editable=False, help_text='Referencia de integridad del perfilamiento con el archivo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prfl.Profiling')),
            ],
            options={
                'verbose_name': 'Archivo de Perfilamiento',
                'verbose_name_plural': 'Archivos de Perfilamiento',
                'permissions': [('Can_View__ProfilingFile', 'Ve archivos de perfilamiento'), ('Can_Create__ProfilingFile', 'Crea archivos de perfilamiento'), ('Can_Update__ProfilingFile', 'Modifica archivos de perfilamiento'), ('Can_Delete__ProfilingFile', 'Elimina archivos de perfilamiento')],
                'abstract': False,
            },
            bases=('quda.file',),
        ),
        migrations.AddField(
            model_name='profiling',
            name='user',
            field=models.ForeignKey(help_text='Referencia de integridad con el usuario que configuro el perfilamiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
