# Generated by Django 3.0.10 on 2020-10-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='dates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='floats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='ints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='nulls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='strings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='uniques',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='checkNull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='checkString',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='checkUnique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcBlank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcDate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcFloat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcInt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcNull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcString',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilingrules',
            name='porcUnique',
            field=models.BooleanField(default=False),
        ),
    ]
