# Generated by Django 3.0.10 on 2020-11-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0002_auto_20201103_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiling',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
