# Generated by Django 3.0.10 on 2020-10-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0002_auto_20201020_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcBlank',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcDate',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcFloat',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcInt',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcNull',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcString',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='porcUnique',
        ),
    ]
