# Generated by Django 3.0.10 on 2020-10-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0003_auto_20201020_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='nulls',
        ),
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='uniques',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='checkNull',
        ),
        migrations.RemoveField(
            model_name='profilingrules',
            name='checkUnique',
        ),
        migrations.AlterField(
            model_name='profilingfile',
            name='profiling',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prfl.Profiling'),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='blanks',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='dates',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='floats',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='ints',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='strings',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
