# Generated by Django 3.0.10 on 2020-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0004_auto_20201021_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='profilingFile',
        ),
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='profilingRule',
        ),
        migrations.DeleteModel(
            name='ProfilingRules',
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='json',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='ProfilingFileColumn',
        ),
    ]
