# Generated by Django 3.0.10 on 2020-10-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0005_auto_20201022_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilingfile',
            name='json',
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='correlations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='duplicates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='missing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='package',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='sample',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='scatter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingfile',
            name='variables',
            field=models.TextField(blank=True, null=True),
        ),
    ]
