# Generated by Django 3.0.10 on 2020-11-03 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ModelBase',
                'verbose_name_plural': 'ModelBase',
                'permissions': [('Can_View__ModelBase', 'Ve modelbase'), ('Can_Create__ModelBase', 'Crea modelbase'), ('Can_Update__ModelBase', 'Modifica modelbase'), ('Can_Delete__ModelBase', 'Elimina modelbase')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'ModelBase',
                'verbose_name_plural': 'ModelBase',
                'permissions': [('Can_View__ModelBase', 'Ve modelbase'), ('Can_Create__ModelBase', 'Crea modelbase'), ('Can_Update__ModelBase', 'Modifica modelbase'), ('Can_Delete__ModelBase', 'Elimina modelbase')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limpieza',
                'verbose_name_plural': 'Limpiezas',
                'permissions': [('Can_View__Cleaning', 'Ve limpiezas'), ('Can_Create__Cleaning', 'Crea limpiezas'), ('Can_Update__Cleaning', 'Modifica limpiezas'), ('Can_Delete__Cleaning', 'Elimina limpiezas')],
                'abstract': False,
            },
        ),
    ]
