# Generated by Django 3.0.10 on 2020-12-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quda', '0004_auto_20201112_1819'),
        ('clng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quda.File')),
                ('initialDateTime', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de inicio de la ejecucion del procesamiento del archivo.', null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de termino de la ejecucion del procesamiento del archivo.', null=True)),
                ('cleaning', models.ForeignKey(blank=True, editable=False, help_text='Referencia de integridad del perfilamiento con el archivo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clng.Cleaning')),
            ],
            options={
                'verbose_name': 'Archivo de Limpieza',
                'verbose_name_plural': 'Archivos de limpieza',
                'permissions': [('Can_View__CleaningFile', 'Ve archivos de limpieza'), ('Can_Create__CleaningFile', 'Crea archivos de limpieza'), ('Can_Update__CleaningFile', 'Modifica archivos de limpieza'), ('Can_Delete__CleaningFile', 'Elimina archivos de limpieza')],
                'abstract': False,
            },
            bases=('quda.file',),
        ),
        migrations.CreateModel(
            name='CleaningFileColumn',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quda.File')),
                ('index', models.PositiveIntegerField()),
                ('cleaningFile', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clng.CleaningFile')),
            ],
            options={
                'verbose_name': 'CleaningFileColumn',
                'verbose_name_plural': 'CleaningFileColumn',
                'permissions': [('Can_View__CleaningFileColumn', 'Ve cleaningfilecolumn'), ('Can_Create__CleaningFileColumn', 'Crea cleaningfilecolumn'), ('Can_Update__CleaningFileColumn', 'Modifica cleaningfilecolumn'), ('Can_Delete__CleaningFileColumn', 'Elimina cleaningfilecolumn')],
                'abstract': False,
            },
            bases=('quda.file',),
        ),
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'CleaningRule',
                'verbose_name_plural': 'CleaningRule',
                'permissions': [('Can_View__CleaningRule', 'Ve cleaningrule'), ('Can_Create__CleaningRule', 'Crea cleaningrule'), ('Can_Update__CleaningRule', 'Modifica cleaningrule'), ('Can_Delete__CleaningRule', 'Elimina cleaningrule')],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BaseRule',
        ),
        migrations.DeleteModel(
            name='CleaningRules',
        ),
        migrations.AddField(
            model_name='cleaningfilecolumn',
            name='cleaningRules',
            field=models.ManyToManyField(to='clng.CleaningRule'),
        ),
    ]
