# Generated by Django 3.0.10 on 2020-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ModelBase',
                'verbose_name_plural': 'ModelBase',
                'permissions': [('Can_View__ModelBase', 'Ve modelbase'), ('Can_Create__ModelBase', 'Crea modelbase'), ('Can_Update__ModelBase', 'Modifica modelbase'), ('Can_Delete__ModelBase', 'Elimina modelbase')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'ModelBase',
                'verbose_name_plural': 'ModelBase',
                'permissions': [('Can_View__ModelBase', 'Ve modelbase'), ('Can_Create__ModelBase', 'Crea modelbase'), ('Can_Update__ModelBase', 'Modifica modelbase'), ('Can_Delete__ModelBase', 'Elimina modelbase')],
                'abstract': False,
            },
        ),
    ]
