# Generated by Django 3.0.10 on 2020-12-04 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('clng', '0002_auto_20201203_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningFileOrderedRulesInColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'CleaningRule',
                'verbose_name_plural': 'CleaningRule',
                'permissions': [('Can_View__CleaningRule', 'Ve cleaningrule'), ('Can_Create__CleaningRule', 'Crea cleaningrule'), ('Can_Update__CleaningRule', 'Modifica cleaningrule'), ('Can_Delete__CleaningRule', 'Elimina cleaningrule')],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cleaningfilecolumn',
            name='cleaningFile',
        ),
        migrations.RemoveField(
            model_name='cleaningfilecolumn',
            name='cleaningRules',
        ),
        migrations.AddField(
            model_name='cleaning',
            name='creationDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleaning',
            name='finalDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='initialDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cleaningfile',
            name='destinationFileName',
            field=models.CharField(blank=True, help_text='ruta destino donde se colocara el nuevo archivo con el resultado de las reglas.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cleaningfilecolumn',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='CleaningRule',
        ),
        migrations.AddField(
            model_name='cleaningfileorderedrulesincolumns',
            name='cleaningFile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clng.CleaningFile'),
        ),
        migrations.AddField(
            model_name='cleaningfileorderedrulesincolumns',
            name='columns',
            field=models.ManyToManyField(blank=True, null=True, to='clng.CleaningFileColumn'),
        ),
        migrations.AddField(
            model_name='cleaningfileorderedrulesincolumns',
            name='rules',
            field=models.ManyToManyField(blank=True, null=True, to='contenttypes.ContentType'),
        ),
    ]
