# Generated by Django 3.0.10 on 2020-12-04 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('clng', '0003_auto_20201203_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningfilecolumn',
            name='cleaningFile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clng.CleaningFile'),
        ),
        migrations.AlterField(
            model_name='cleaningfileorderedrulesincolumns',
            name='columns',
            field=models.ManyToManyField(blank=True, to='clng.CleaningFileColumn'),
        ),
        migrations.AlterField(
            model_name='cleaningfileorderedrulesincolumns',
            name='rules',
            field=models.ManyToManyField(blank=True, to='contenttypes.ContentType'),
        ),
    ]
