# Generated by Django 3.0.10 on 2020-12-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quda', '0004_auto_20201112_1819'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('clng', '0006_baserule_cleanallrule_dateformatrule_formatdecimalrule_initcaprule_lengthrule_lowerrule_lpadrule_ltr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningFileRule',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quda.File')),
                ('object_id', models.PositiveIntegerField()),
                ('cleaningFile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clng.CleaningFile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'CleaningFileRule',
                'verbose_name_plural': 'CleaningFileRule',
                'permissions': [('Can_View__CleaningFileRule', 'Ve cleaningfilerule'), ('Can_Create__CleaningFileRule', 'Crea cleaningfilerule'), ('Can_Update__CleaningFileRule', 'Modifica cleaningfilerule'), ('Can_Delete__CleaningFileRule', 'Elimina cleaningfilerule')],
                'abstract': False,
            },
            bases=('quda.file',),
        ),
        migrations.AlterField(
            model_name='cleaningfileorderedrulesincolumns',
            name='rules',
            field=models.ManyToManyField(blank=True, to='clng.CleaningFileRule'),
        ),
    ]
