# Generated by Django 3.0.10 on 2020-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
