# Generated by Django 3.0.10 on 2020-10-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('creationDateTime', models.DateTimeField(auto_now_add=True)),
                ('initialDateTime', models.DateTimeField(blank=True, null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfilamiento',
                'verbose_name_plural': 'Perfilamientos',
                'permissions': [('Can_View__Profiling', 'Ve perfilamientos'), ('Can_Create__Profiling', 'Crea perfilamientos'), ('Can_Update__Profiling', 'Modifica perfilamientos'), ('Can_Delete__Profiling', 'Elimina perfilamientos')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilingFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quda.File')),
                ('isblank', models.BooleanField(default=False)),
                ('initialDateTime', models.DateTimeField(blank=True, null=True)),
                ('finalDateTime', models.DateTimeField(blank=True, null=True)),
                ('profiling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiling.Profiling')),
            ],
            options={
                'verbose_name': 'ModelBase',
                'verbose_name_plural': 'ModelBase',
                'permissions': [('Can_View__ModelBase', 'Ve modelbase'), ('Can_Create__ModelBase', 'Crea modelbase'), ('Can_Update__ModelBase', 'Modifica modelbase'), ('Can_Delete__ModelBase', 'Elimina modelbase')],
                'abstract': False,
            },
            bases=('quda.file',),
        ),
        migrations.CreateModel(
            name='ProfilingFileColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('columnIndex', models.IntegerField(default=0)),
                ('header', models.CharField(max_length=500)),
                ('blanks', models.IntegerField(default=0)),
                ('integers', models.IntegerField(default=0)),
                ('profilingFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiling.ProfilingFile')),
            ],
            options={
                'verbose_name': 'ModelBase',
                'verbose_name_plural': 'ModelBase',
                'permissions': [('Can_View__ModelBase', 'Ve modelbase'), ('Can_Create__ModelBase', 'Crea modelbase'), ('Can_Update__ModelBase', 'Modifica modelbase'), ('Can_Delete__ModelBase', 'Elimina modelbase')],
                'abstract': False,
            },
        ),
    ]
