# Generated by Django 3.0.10 on 2020-10-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('checkBlank', models.BooleanField(default=False)),
                ('checkFloat', models.BooleanField(default=False)),
                ('checkInt', models.BooleanField(default=False)),
                ('checkDate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Regla de perfilamiento',
                'verbose_name_plural': 'Reglas de perfilamiento',
                'permissions': [('Can_View__ProfilingRules', 'Ve reglas de perfilamiento'), ('Can_Create__ProfilingRules', 'Crea reglas de perfilamiento'), ('Can_Update__ProfilingRules', 'Modifica reglas de perfilamiento'), ('Can_Delete__ProfilingRules', 'Elimina reglas de perfilamiento')],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='profilingfile',
            options={'permissions': [('Can_View__ProfilingFile', 'Ve archivos de perfilamiento'), ('Can_Create__ProfilingFile', 'Crea archivos de perfilamiento'), ('Can_Update__ProfilingFile', 'Modifica archivos de perfilamiento'), ('Can_Delete__ProfilingFile', 'Elimina archivos de perfilamiento')], 'verbose_name': 'Archivo de Perfilamiento', 'verbose_name_plural': 'Archivos de Perfilamiento'},
        ),
        migrations.AlterModelOptions(
            name='profilingfilecolumn',
            options={'permissions': [('Can_View__ProfilingFileColumn', 'Ve columnas de archivos de perfilamiento'), ('Can_Create__ProfilingFileColumn', 'Crea columnas de archivos de perfilamiento'), ('Can_Update__ProfilingFileColumn', 'Modifica columnas de archivos de perfilamiento'), ('Can_Delete__ProfilingFileColumn', 'Elimina columnas de archivos de perfilamiento')], 'verbose_name': 'Columna de archivos de perfilamiento', 'verbose_name_plural': 'Columnas de archivos de perfilamiento'},
        ),
        migrations.RemoveField(
            model_name='profilingfile',
            name='isblank',
        ),
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='blanks',
        ),
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='header',
        ),
        migrations.RemoveField(
            model_name='profilingfilecolumn',
            name='integers',
        ),
        migrations.AlterField(
            model_name='profiling',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='profilingfile',
            name='finalDateTime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profilingfile',
            name='initialDateTime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='profilingfilecolumn',
            name='profilingFile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiling.ProfilingFile'),
        ),
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='profilingRule',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='profiling.ProfilingRules'),
            preserve_default=False,
        ),
    ]
