# Generated by Django 3.0.10 on 2020-10-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_auto_20201016_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingfilecolumn',
            name='blanks',
            field=models.IntegerField(default=0),
        ),
    ]
