# Generated by Django 3.0.10 on 2020-11-03 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('filename', models.CharField(help_text="Nombre del archivo con 'path' completo", max_length=500)),
                ('sep', models.CharField(default=',', help_text="Caracter utilizado como separador de los datos entre cada columna; ej. '^'", max_length=1)),
                ('encoding', models.CharField(default='latin1', help_text="Metodo de codificación de caracteres; ej. 'latin1'", max_length=50)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'permissions': [('Can_View__File', 'Ve archivos'), ('Can_Create__File', 'Crea archivos'), ('Can_Update__File', 'Modifica archivos'), ('Can_Delete__File', 'Elimina archivos')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(help_text='Nombre de la mascara', max_length=50)),
                ('code', models.CharField(help_text='Código de la mascara', max_length=50)),
                ('regex', models.TextField(help_text='Expresion regular')),
                ('isValid', models.BooleanField(default=False, help_text='Es valida la expresion regular?')),
                ('isDefault', models.BooleanField(default=False, help_text='Se puede modificar?')),
                ('organzation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Dato',
                'verbose_name_plural': 'Tipos de Dato',
                'permissions': [('Can_View__DataType', 'Ve tipos de dato'), ('Can_Create__DataType', 'Crea tipos de dato'), ('Can_Update__DataType', 'Modifica tipos de dato'), ('Can_Delete__DataType', 'Elimina tipos de dato')],
                'abstract': False,
            },
        ),
    ]
