# Generated by Django 3.0.10 on 2020-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('filename', models.CharField(max_length=500)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('separatorType', models.CharField(max_length=1)),
                ('newline', models.CharField(blank=True, default='', max_length=5)),
                ('delimiter', models.CharField(default=',', max_length=1)),
                ('encoding', models.CharField(default='latin1', max_length=50)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'permissions': [('Can_View__File', 'Ve archivos'), ('Can_Create__File', 'Crea archivos'), ('Can_Update__File', 'Modifica archivos'), ('Can_Delete__File', 'Elimina archivos')],
                'abstract': False,
            },
        ),
    ]
