# Generated by Django 3.0.10 on 2020-10-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='delimiter',
            new_name='sep',
        ),
        migrations.RemoveField(
            model_name='file',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='file',
            name='newline',
        ),
        migrations.RemoveField(
            model_name='file',
            name='quotechar',
        ),
        migrations.RemoveField(
            model_name='file',
            name='rows',
        ),
    ]
