# Generated by Django 3.0.10 on 2020-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='columns',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(help_text="Nombre del archivo con 'path' completo", max_length=500),
        ),
        migrations.AlterField(
            model_name='file',
            name='rows',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
