# Generated by Django 3.0.10 on 2020-10-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quda', '0002_auto_20201016_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='separatorType',
            new_name='quotechar',
        ),
    ]
