# Generated by Django 3.0.10 on 2020-11-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quda', '0002_file_haveheaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHeaderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('index', models.IntegerField()),
                ('headerName', models.CharField(max_length=250)),
                ('dataType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quda.DataType')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quda.File')),
            ],
            options={
                'verbose_name': 'Tipo de Dato en cabecera',
                'verbose_name_plural': 'Tipo de Dato en cabecera',
                'permissions': [('Can_View__TypeHeaderFile', 'Ve tipo de dato en cabecera'), ('Can_Create__TypeHeaderFile', 'Crea tipo de dato en cabecera'), ('Can_Update__TypeHeaderFile', 'Modifica tipo de dato en cabecera'), ('Can_Delete__TypeHeaderFile', 'Elimina tipo de dato en cabecera')],
                'abstract': False,
            },
        ),
    ]
