# Generated by Django 3.0.10 on 2020-11-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quda', '0003_typeheaderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeheaderfile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quda.File'),
        ),
    ]
