# Generated by Django 3.0.10 on 2020-10-19 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pareo',
                'verbose_name_plural': 'Pareos',
                'permissions': [('Can_View__Matching', 'Ve pareos'), ('Can_Create__Matching', 'Crea pareos'), ('Can_Update__Matching', 'Modifica pareos'), ('Can_Delete__Matching', 'Elimina pareos')],
                'abstract': False,
            },
        ),
    ]
